### ISSUE TITLE
[FEATURE] : 메인페이지 UIMenu '갤러리에서 추가하기' 버튼 기능 구현

### ISSUE THREAD

**Issue by kwangjo93** [TeamPoki/Poki-iOS#14]
## Description
> 어떤 작업을 진행할지 간단하게 내용 작성하세요.
메인페이지 UIMenu '갤러리에서 추가하기' 버튼 기능 구현
## Task
> 진행하는 작업을 작은 단위로 분리해서 작성하세요.

- [x] 버튼 클릭 시 갤러리로 이동
- [x] requestAuthorization 포토 권한 묻는 메서드

## ETC
> 기타 참고사항이 있으면 작성하세요.

**Comment by playhong16** [comment]
고생하셨습니다!
