### ISSUE TITLE
[MAINTENANCE] userDataManager 리펙토링

### ISSUE THREAD

**Issue by kwangjo93** [TeamPoki/Poki-iOS#154]
## Description

뷰컨트롤러의 코드를 더 간결하게 하기 위해

## Where
> 어디에 위치한 파일인가요?

userDataManager

## Which parts
> Where 파일의 어느 부분을 리팩토링할 예정인가요?

## Expactation
> 리팩토링 후 예상되는 부분에 대한 내용을 작성하세요.

뷰컨트롤러의 코드를 더 간결

**Comment by playhong16** [comment]
고생하셨슴다!
