### ISSUE TITLE
[FEATURE] : addPhotoView textField 키보드 뷰 조정

### ISSUE THREAD

**Issue by kwangjo93** [TeamPoki/Poki-iOS#37]
## Description
> 어떤 작업을 진행할지 간단하게 내용 작성하세요.
[FEATURE] : addPhotoView textField 키보드 뷰 조정
## Task
> 진행하는 작업을 작은 단위로 분리해서 작성하세요.

- [x] 텍스트필드 입력 시 올라오면 뷰를 조정(해당 텍스트 필드가 보이도록)

## ETC
> 기타 참고사항이 있으면 작성하세요.

**Comment by playhong16** [comment]
고생하셨습니다!
