### ISSUE TITLE
[FEATURE] addPhotoView UIImage backgroundView 설정

### ISSUE THREAD

**Issue by kwangjo93** [TeamPoki/Poki-iOS#43]
## Description
> 어떤 작업을 진행할지 간단하게 내용 작성하세요.
[FEATURE] addPhotoView UIImage backgroundView 설정
## Task
> 진행하는 작업을 작은 단위로 분리해서 작성하세요.

- [x] addPhotoView UIImage 크기에 맞추어 backgroundView 설정

## ETC
> 기타 참고사항이 있으면 작성하세요.

**Comment by playhong16** [comment]
고생하셨습니다.
