### ISSUE TITLE
[FEATURE] addPhotoViewController에서 Creat, update 구현

### ISSUE THREAD

**Issue by kwangjo93** [TeamPoki/Poki-iOS#64]
## Description
> 어떤 작업을 진행할지 간단하게 내용 작성하세요.
[FEATURE] addPhotoViewController에서 Creat, update 구현
## Task
> 진행하는 작업을 작은 단위로 분리해서 작성하세요.

- [x] Creat 메서드
- [x] update
- [x] enum (new, edit)  구분

## ETC
> 기타 참고사항이 있으면 작성하세요.

**Comment by playhong16** [comment]
고생하셨습니다!
