### ISSUE TITLE
[MAINTENANCE] addPhotoView 오토레이아웃 경고 수정

### ISSUE THREAD

**Issue by kwangjo93** [TeamPoki/Poki-iOS#83]
## Description

- 왜 이 작업을 수행하려고 하는지 간단한 근거와 설명 작성하세요.
오토레이아웃 경고표시가 나서 적절하게 수정하려 합니다.

## Where
> 어디에 위치한 파일인가요?

- addPhotoView

## Which parts
> Where 파일의 어느 부분을 리팩토링할 예정인가요?

- `오토레이아웃 메서드

## Expactation
> 리팩토링 후 예상되는 부분에 대한 내용을 작성하세요.

- 콘솔 창 경고표시 제거

**Comment by playhong16** [comment]
고생하셨습니다!
