### ISSUE TITLE
[MAINTENANCE]: SettingsViewController 폰트 변경

### ISSUE THREAD

**Issue by Taeshiki** [TeamPoki/Poki-iOS#84]
## Description

- 다른 페이지와 통일성을 위해 폰트 변경

## Where

- `SettingsViewController`
- `NoticeListViewController`

## Which parts

- `SettingsViewController`[17줄, 46-49줄, 103줄]
- `NoticeListViewController`[18-19줄, 48-51줄, 69-73줄]

## Expactation
> 리팩토링 후 예상되는 부분에 대한 내용을 작성하세요.

- 화면전환시 다른페이지와 폰트 통일성 유지

**Comment by playhong16** [comment]
고생하셨슴다!
