### ISSUE TITLE
[FEATURE]  addPhtoView 제스처 및 피커뷰 구현

### ISSUE THREAD

**Issue by kwangjo93** [TeamPoki/Poki-iOS#9]
## Description
> 어떤 작업을 진행할지 간단하게 내용 작성하세요.
addPhtoView의 이미지를 누르면 제스처와 함께 이미지피커뷰 구현
## Task
> 진행하는 작업을 작은 단위로 분리해서 작성하세요.

- [x] 제스처 + 이미지 피커뷰
- [x] plist 설정

## ETC
> 기타 참고사항이 있으면 작성하세요.

**Comment by playhong16** [comment]
고생하셨습니다!
